
import json
import logging
import logging.config


def setupLogging(level):

    with open('config/log.json', 'r') as log_conf:
        json_conf = json.loads(log_conf.read())
        logging.config.dictConfig(json_conf)

''' #############################################
     Core Log
    #############################################
    All information generated by Swarming's core
    system(executors, core, engine, messenger, etc)
    is logged with this logger.
'''
'''
core_log = logging.getLogger('core')
core_log.setLevel(level=logging.ERROR)

handler = logging.StreamHandler()
handler.setLevel(stream_log_level)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

handler.setFormatter(formatter)
'''
#logger.addHandler(handler)

''' #############################################
     Units Log
    #############################################
    All information generated by Light Units
    (SSH, HTTP, FTP, etc) should be logged by this
    logger.
'''
'''
unit_log = logging.getLogger('unit')
unit_log.setLevel(level=logging.ERROR)
'''
''' #############################################
     User Log
    #############################################
    The information this logger get is all that
    could be interesting for final user.
'''
'''
user_log = logging.getLogger('user')
user_log.setLevel(level=logging.ERROR)
'''